import { z, ZodTypeAny } from 'zod';
import {
  MesEventType,
  BatchStartedPayloadSchema,
  StateChangedPayloadSchema,
  DowntimeRecordedPayloadSchema,
  MaterialConsumedPayloadSchema,
  OutputRecordedPayloadSchema,
  BatchCompletedPayloadSchema,
  PanelCheckoutPayloadSchema,
  ReelSplicedPayloadSchema,
  PickErrorPayloadSchema,
  ReelUnsealedPayloadSchema,
  ReelDryStorageEnteredPayloadSchema,
  ReelDryStorageExitedPayloadSchema,
  ReelBakeStartedPayloadSchema,
  ReelBakeCompletedPayloadSchema,
  ReelResealedPayloadSchema,
  QualityGateBlockedPayloadSchema,
  QualityGatePassedPayloadSchema,
  PasteRemovedFromColdPayloadSchema,
  PasteThawVerifiedPayloadSchema,
  PasteMixedPayloadSchema,
  PasteAuthorizedPayloadSchema,
  PasteLoadedOnStencilPayloadSchema,
  PasteRemovedFromStencilPayloadSchema,
  PasteDiscardedPayloadSchema,
  StencilSessionStartedPayloadSchema,
  StencilSessionEndedPayloadSchema,
  AoiInspectionCompletedPayloadSchema,
  SpiInspectionCompletedPayloadSchema,
  DefectRecordedPayloadSchema,
  QualityHoldAppliedPayloadSchema,
  QualityDispositionDecidedPayloadSchema,
  ReworkStartedPayloadSchema,
  ComponentReplacedPayloadSchema,
  PostReworkInspectionCompletedPayloadSchema,
  ReworkCompletedPayloadSchema,
  RepeatDefectInterlockTrippedPayloadSchema,
  PanelScrappedPayloadSchema,
  SpiInspectionRecordedPayloadSchema,
  PrinterCleaningCommandedPayloadSchema,
  PrinterParametersModifiedPayloadSchema,
  PrinterCommandAcknowledgedPayloadSchema,
  ClosedLoopCorrectionVerifiedPayloadSchema,
  PreReflowPanelDivertedPayloadSchema,
  AgvMissionDispatchedPayloadSchema,
  AgvMissionStateChangedPayloadSchema,
  AgvMissionBlockedPayloadSchema,
  AgvMissionFailedPayloadSchema,
  AgvMissionCompletedPayloadSchema,
  MaterialReplenishmentRequestedPayloadSchema,
  MaterialReservedPayloadSchema,
  MaterialDeliveredPayloadSchema,
  PredictiveAnomalyDetectedPayloadSchema,
  PredictiveActionRecommendedPayloadSchema,
  PredictiveActionAuthorizedPayloadSchema,
  PredictiveActionExecutedPayloadSchema,
  PredictiveActionFailedPayloadSchema,
  ReflowProfileUploadedPayloadSchema,
  ReflowProfileValidatedPayloadSchema,
  ReflowProfileComplianceEvaluatedPayloadSchema,
  ReflowProfileApprovedPayloadSchema,
  ReflowProfileRejectedPayloadSchema,
  ReflowProfileActivatedPayloadSchema,
  ReflowProfileRetiredPayloadSchema,
  ReflowDriftDetectedPayloadSchema,
  ReflowProcessStateChangedPayloadSchema,
  ReflowInterlockRequestedPayloadSchema,
  ReflowInterlockConfirmedPayloadSchema,
  ReflowInterlockFailedPayloadSchema,
  ReflowRevalidationRequestedPayloadSchema
} from '@mes/shared';

export class EventSchemaRegistry {
  private static registry: Map<MesEventType, ZodTypeAny> = new Map<MesEventType, ZodTypeAny>([
    ['BATCH_STARTED', BatchStartedPayloadSchema],
    ['STATE_CHANGED', StateChangedPayloadSchema],
    ['DOWNTIME_RECORDED', DowntimeRecordedPayloadSchema],
    ['MATERIAL_CONSUMED', MaterialConsumedPayloadSchema],
    ['OUTPUT_RECORDED', OutputRecordedPayloadSchema],
    ['BATCH_COMPLETED', BatchCompletedPayloadSchema],
    ['PANEL_CHECKOUT', PanelCheckoutPayloadSchema],
    ['REEL_SPLICED', ReelSplicedPayloadSchema],
    ['PICK_ERROR_RECORDED', PickErrorPayloadSchema],
    ['REEL_UNSEALED', ReelUnsealedPayloadSchema],
    ['REEL_DRY_STORAGE_ENTERED', ReelDryStorageEnteredPayloadSchema],
    ['REEL_DRY_STORAGE_EXITED', ReelDryStorageExitedPayloadSchema],
    ['REEL_BAKE_STARTED', ReelBakeStartedPayloadSchema],
    ['REEL_BAKE_COMPLETED', ReelBakeCompletedPayloadSchema],
    ['REEL_RESEALED', ReelResealedPayloadSchema],
    ['QUALITY_GATE_BLOCKED', QualityGateBlockedPayloadSchema],
    ['QUALITY_GATE_PASSED', QualityGatePassedPayloadSchema],
    ['PASTE_REMOVED_FROM_COLD', PasteRemovedFromColdPayloadSchema],
    ['PASTE_THAW_VERIFIED', PasteThawVerifiedPayloadSchema],
    ['PASTE_MIXED', PasteMixedPayloadSchema],
    ['PASTE_AUTHORIZED', PasteAuthorizedPayloadSchema],
    ['PASTE_LOADED_ON_STENCIL', PasteLoadedOnStencilPayloadSchema],
    ['PASTE_REMOVED_FROM_STENCIL', PasteRemovedFromStencilPayloadSchema],
    ['PASTE_DISCARDED', PasteDiscardedPayloadSchema],
    ['STENCIL_SESSION_STARTED', StencilSessionStartedPayloadSchema],
    ['STENCIL_SESSION_ENDED', StencilSessionEndedPayloadSchema],
    ['AOI_INSPECTION_COMPLETED', AoiInspectionCompletedPayloadSchema],
    ['SPI_INSPECTION_COMPLETED', SpiInspectionCompletedPayloadSchema],
    ['DEFECT_RECORDED', DefectRecordedPayloadSchema],
    ['QUALITY_HOLD_APPLIED', QualityHoldAppliedPayloadSchema],
    ['QUALITY_DISPOSITION_DECIDED', QualityDispositionDecidedPayloadSchema],
    ['REWORK_STARTED', ReworkStartedPayloadSchema],
    ['COMPONENT_REPLACED', ComponentReplacedPayloadSchema],
    ['POST_REWORK_INSPECTION_COMPLETED', PostReworkInspectionCompletedPayloadSchema],
    ['REWORK_COMPLETED', ReworkCompletedPayloadSchema],
    ['REPEAT_DEFECT_INTERLOCK_TRIPPED', RepeatDefectInterlockTrippedPayloadSchema],
    ['PANEL_SCRAPPED', PanelScrappedPayloadSchema],
    ['SPI_INSPECTION_RECORDED', SpiInspectionRecordedPayloadSchema],
    ['PRINTER_CLEANING_COMMANDED', PrinterCleaningCommandedPayloadSchema],
    ['PRINTER_PARAMETERS_MODIFIED', PrinterParametersModifiedPayloadSchema],
    ['PRINTER_COMMAND_ACKNOWLEDGED', PrinterCommandAcknowledgedPayloadSchema],
    ['CLOSED_LOOP_CORRECTION_VERIFIED', ClosedLoopCorrectionVerifiedPayloadSchema],
    ['PRE_REFLOW_PANEL_DIVERTED', PreReflowPanelDivertedPayloadSchema],
    ['AGV_MISSION_DISPATCHED', AgvMissionDispatchedPayloadSchema],
    ['AGV_MISSION_STATE_CHANGED', AgvMissionStateChangedPayloadSchema],
    ['AGV_MISSION_BLOCKED', AgvMissionBlockedPayloadSchema],
    ['AGV_MISSION_FAILED', AgvMissionFailedPayloadSchema],
    ['AGV_MISSION_COMPLETED', AgvMissionCompletedPayloadSchema],
    ['MATERIAL_REPLENISHMENT_REQUESTED', MaterialReplenishmentRequestedPayloadSchema],
    ['MATERIAL_RESERVED', MaterialReservedPayloadSchema],
    ['MATERIAL_DELIVERED', MaterialDeliveredPayloadSchema],
    ['PREDICTIVE_ANOMALY_DETECTED', PredictiveAnomalyDetectedPayloadSchema],
    ['PREDICTIVE_ACTION_RECOMMENDED', PredictiveActionRecommendedPayloadSchema],
    ['PREDICTIVE_ACTION_AUTHORIZED', PredictiveActionAuthorizedPayloadSchema],
    ['PREDICTIVE_ACTION_EXECUTED', PredictiveActionExecutedPayloadSchema],
    ['PREDICTIVE_ACTION_FAILED', PredictiveActionFailedPayloadSchema],
    // Phase 6
    ['REFLOW_PROFILE_UPLOADED', ReflowProfileUploadedPayloadSchema],
    ['REFLOW_PROFILE_VALIDATED', ReflowProfileValidatedPayloadSchema],
    ['REFLOW_PROFILE_COMPLIANCE_EVALUATED', ReflowProfileComplianceEvaluatedPayloadSchema],
    ['REFLOW_PROFILE_APPROVED', ReflowProfileApprovedPayloadSchema],
    ['REFLOW_PROFILE_REJECTED', ReflowProfileRejectedPayloadSchema],
    ['REFLOW_PROFILE_ACTIVATED', ReflowProfileActivatedPayloadSchema],
    ['REFLOW_PROFILE_RETIRED', ReflowProfileRetiredPayloadSchema],
    ['REFLOW_DRIFT_DETECTED', ReflowDriftDetectedPayloadSchema],
    ['REFLOW_PROCESS_STATE_CHANGED', ReflowProcessStateChangedPayloadSchema],
    ['REFLOW_INTERLOCK_REQUESTED', ReflowInterlockRequestedPayloadSchema],
    ['REFLOW_INTERLOCK_CONFIRMED', ReflowInterlockConfirmedPayloadSchema],
    ['REFLOW_INTERLOCK_FAILED', ReflowInterlockFailedPayloadSchema],
    ['REFLOW_REVALIDATION_REQUESTED', ReflowRevalidationRequestedPayloadSchema]
  ]);

  public static registerSchema(eventType: MesEventType, schema: ZodTypeAny): void {
    this.registry.set(eventType, schema);
  }

  public static getSchema(eventType: MesEventType): ZodTypeAny | undefined {
    return this.registry.get(eventType);
  }

  public static validate(eventType: MesEventType, payload: any): any {
    const schema = this.registry.get(eventType);
    if (!schema) {
      // If no specific payload schema registered, allow arbitrary object
      return payload;
    }
    return schema.parse(payload);
  }
}
