apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smt-mes.fullname" . }}-config
  labels:
    {{- include "smt-mes.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.global.environment | quote }}
  PORT: {{ .Values.api.env.PORT | quote }}
  FUJI_PORT: {{ .Values.api.env.FUJI_PORT | quote }}
  FACTORY_SITE: {{ .Values.global.factorySite | quote }}
  LOG_LEVEL: {{ .Values.api.env.LOG_LEVEL | quote }}
