apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smt-mes.fullname" . }}-web
  labels:
    {{- include "smt-mes.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "smt-mes.webSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "smt-mes.webSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mes-web
          securityContext:
            {{- toYaml .Values.web.securityContext | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
