{{- if .Values.api.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "smt-mes.fullname" . }}-data
  labels:
    {{- include "smt-mes.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.api.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.api.persistence.size | default "10Gi" }}
  {{- if .Values.api.persistence.storageClass }}
  storageClassName: {{ .Values.api.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
