apiVersion: v1
kind: Service
metadata:
  name: {{ include "smt-mes.fullname" . }}-web
  labels:
    {{- include "smt-mes.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "smt-mes.webSelectorLabels" . | nindent 4 }}
